### ISSUE TITLE
ClientClosedError: The client is closed

### ISSUE THREAD

**Issue by HuyAms** [mannyv123/cachified-redis-adapter#21]
Hi, I followed the example in the doc 

```
import {createClient} from 'redis'
import {redisCacheAdapter} from 'cachified-redis-adapter

const redis = createClient({
  /* ...opts */
})
const cache = redisCacheAdapter(redis)

await cachified({
  cache,
  key: 'user-1',
  getFreshValue() {
    return 'user@example.org'
  },
  /* ...opts */
})
```

However, I got the error `ClientClosedError: The client is closed`

Where should I call the  `await redis.connect();`?

**Comment by mannyv123** [comment]
Hi @HuyAms!

You're most likely running into that error because you haven't connected to the redis client before trying to use the cache.

A quick way just to get the cache working would be testing it out like this:

```
const client = createClient({ 
     /* ...opts */
 });

client
   .connect()
   .then(() => console.log("redis is connected"))
   .catch((error) => console.error(error));

const cache = redisCacheAdapter(client);
```

and then using that `cache` with `cachified`. 

Ultimately how you set up and connect to your redis client is dependent on your application and preferences.

Hope this helps!
